### ISSUE TITLE
Unexpected alignments

### ISSUE THREAD

**Issue by jdidion** [fulcrumgenomics/stitch#48]
Attached is a single read from Simpson et al. '23. The vector sequence is also attached, as well as the alignments in SAM format. There are two unexpected things about these alignments:

1. There are 11 reads but only 1 is marked supplementary. The other 10 are neither secondary nor supplementary. (I am using `feat-44-sam-flags-and-tags` branch).
2. Several of the alignments are contiguous without gaps - these should be a single alignment.

[test_data.tgz](https://github.com/fulcrumgenomics/stitch/files/12652294/test_data.tgz)

**Comment by jdidion** [comment]
For reference, here are the minimap2 alignments
[minimap_test.sam.gz](https://github.com/fulcrumgenomics/stitch/files/12652307/minimap_test.sam.gz)

**Comment by nh13** [comment]
Fixed in https://github.com/fulcrumgenomics/stitch/pull/46/commits/c6bd79f271aca547bd5358bb9f84d2a5cbdd08bf

Also, here's some settings that penalize the jumps a bit more, which seems to make a difference.
```
	--jump-score-same-contig-and-strand -40 \
	--jump-score-same-contig-opposite-strand -80 \
	--jump-score-inter-contig -160 \
```

Let me know if this works for you and we can close this issue.

**Comment by nh13** [comment]
Perhaps we should change the defaults in the tool as well?

**Comment by jdidion** [comment]
Yes, the commit fixes the flags issue, and those parameters fix the split alignment issue.

I like the idea of tuning the jump parameters individually (right now all are set to `-10`), but maybe we should see a few more cases before deciding. I'll open a separate tracking issue for that.
